apiVersion: webapp.my.domain/v1
kind: User
metadata:
  labels:
    app.kubernetes.io/name: users-operator
    app.kubernetes.io/managed-by: kustomize
  name: user-sample
spec:
  # TODO(user): Add fields here
