// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package database

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, name, age)
VALUES ($1, $2, $3)
RETURNING id, name, age
`

type CreateUserParams struct {
	ID   int64
	Name string
	Age  int64
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.ID, arg.Name, arg.Age)
	var i User
	err := row.Scan(&i.ID, &i.Name, &i.Age)
	return i, err
}
